version: 1.0
component: deployment
runAs: root
env:
variables:
files:
# This section is to define how the files in the artifact shall
# be put on the compute instance
- source: /opdemo.war
destination: /u01/devops/
- source: /manageApplication.py
destination: /u01/devops/
- source: /deployapp.sh
destination: /u01/devops/

steps:
# This section is to define the scripts that each step shall run on the instance - stepType: Command
name: Chmod Script
command: "chmod +x /u01/devops/deployapp.sh"
runAs: opc
timeoutInSeconds: 60
- stepType: Command
name: Run script
command: "/u01/devops/deployapp.sh"
runAs: opc
timeoutInSeconds: 60