version: 1.0
component: deployment
runAs: root
env: 
  variables: 
    version: ${DEPLOY_VERSION}
files:   
   - source: /opdemo.war
    destination: /u01/devops/
   - source: /manageApplication.py
    destination: /u01/devops/
   - source: /deployapp.sh
    destination: /u01/devops/
steps: 
  - stepType: Command
    name: Chmod Script
    command: chmod +x /u01/devops/deployapp.sh
    timeoutInSeconds: 600
  - stepType: Command
    name: Run wlst script and deploy
    command: /u01/devops/deployapp.sh
    timeoutInSeconds: 600